name: movie_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.6.3
  hydrated_bloc: ^10.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  skeletonizer: ^1.4.3
  infinite_scroll_pagination: ^4.1.0
  cached_network_image: ^3.4.1
  flutter_bounceable: ^1.2.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env
    # Add assets from the images directory to the application.
    - assets/images/
